{
 "title": "K8s Pod States",
 "tags": [
  "bluescape",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "label_values(up, namespace)" },
   { "name": "phase", "label": "Pod State", "query": "label_values(phase)" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_pod_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Pods in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase == 1)"
    }
   ]
  },
  {
   "title": "Running Pods in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"} == 1)"
    }
   ]
  },
  {
   "title": "Pending Pods in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Pending\"} == 1)"
    }
   ]
  },
  {
   "title": "Failed Pods in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"} == 1)"
    }
   ]
  },
  {
   "title": "Terminating Pods in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Terminating\"} == 1)"
    }
   ]
  },
  {
   "title": "Pods in Unknown State in Cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Unknown\"} == 1)"
    }
   ]
  },
  {
   "title": "Pod Count / Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_status_phase == 1) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "K8s Pod States",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "  max(\n    kube_pod_info{namespace=~\"${namespace}\", node=~\"${node}\"}\n    + on(pod) group_left(phase) \n    max(\n      kube_pod_status_phase{namespace=~\"${namespace}\", phase=~\"${phase}\", phase!=\"Unknown\"} == 1\n      ) by (pod, phase)\n  ) by (node, namespace, pod, pod_ip, phase)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}