# Default values for bluescape-eks-aux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vault:
  enabled: false
  #domain_name: ${domain_name}
  #cluster_id: ${cluster_id}

cert_manager:
  setup_letsencrypt_prod_cluster_issuer: false
  setup_letsencrypt_prod_cluster_dns_issuer: false
  setup_legacy_letsencrypt_old_prod_cluster_issuer:
    enabled: false
    access_key_id: ABCDEFXXXXXXX
    region: us-east-1
    dns_zone: bluescape.com
    hosted_zone_id: ''
    email: ops@bluescape.com
    role: ''
    cname_strategy: None
    acme_server: 'https://acme-v02.api.letsencrypt.org/directory' # Production URL
    #acme_server: 'https://acme-staging-v02.api.letsencrypt.org/directory' # Staging URL for Testing

external_secrets:
  setup_legacy_old_prod_cluster_issuer_secret: false
  setup_gatekeeper_policy_manager_secret: false
  setup_prometheus_metrics_secret: false
  setup_threatstack_secret: false
  setup_argocd_secret: false
  setup_github_secret: false
  setup_loki_secret: false

kubedb_catalog:
  setup_mongodb_3_6: false
  setup_mongodb_4_0: false
  setup_mysql_5_6: false
  setup_postgres_11_1: false

