# Default values for bluescape-eks-aux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vault:
  enabled: false
  #domain_name: ${domain_name}
  #cluster_id: ${cluster_id}

cert_manager:
  setup_letsencrypt_prod_cluster_issuer: false
  setup_letsencrypt_prod_cluster_dns_issuer: false

external_secrets:
  setup_gatekeeper_policy_manager_secret: false
  setup_prometheus_metrics_secret: false
  setup_argocd_secret: false
  setup_github_secret: false
  setup_loki_secret: false
