apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdata.fullname" . }}
  labels:
    {{- include "cdata.labels" . | nindent 4 }}
type: Opaque
data:
  syncRealm.properties: {{ include "cdata.syncRealmPropertiesFileB64Encoded" . }}
