apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdata.fullname" . }}
  # to support vault secret mutation https://confluence.common.bluescape.com/confluence/display/DEVOPS/vault-operator+and+vault-secrets-webhook
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.vault:8200
    vault.security.banzaicloud.io/vault-role: secretsmutation
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/inline-mutation: 'true'
  labels:
    {{- include "cdata.labels" . | nindent 4 }}
type: Opaque
data:
  syncRealm.properties: {{ include "cdata.syncRealmPropertiesFileB64Encoded" . }}
