{{- if .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name:   "legacy-letsencrypt-old-prod-dns"
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    email: {{ .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.email }}
    privateKeySecretRef:
      name: legacy-letsencrypt-old-prod-dns
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.dns_zone | quote }}
      dns01:
        route53:
          region: {{ .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.region }}
          role: {{ .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.role }}
          accessKeyID: {{ .Values.cert_manager.setup_legacy_letsencrypt_old_prod_cluster_issuer.access_key_id }}
          secretAccessKeySecretRef:
            name: legacycertmanager
            key: secretAccessKey
{{- end }}