{{- if .Values.external_secrets.setup_aes_edge_stack_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "edge-stack-license"
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - name: license-key
      key: secret/data/aes-edge-stack
      property: license-key
{{- end }}