{{- if .Values.external_secrets.setup_gatekeeper_policy_manager_secret }}
apiVersion: 'kubernetes-client.io/v1'
kind: 'ExternalSecret'
metadata:
  name: "gpm-secrets"
  namespace: gatekeeper-system
  labels:
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
  data:
    - key: secret/data/oidc/dex
      name: oidc.dex.clientId
      property: clientId
    - key: secret/data/oidc/dex
      name: oidc.dex.clientSecret
      property: clientSecret
{{- end }}