{{- if .Values.external_secrets.setup_loki_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-loki-basic-auth"
  namespace: loki
  labels:
    app: {{ template "bluescape-eks-aux.name" . }}
    chart: {{ template "bluescape-eks-aux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
data:
  - name: loki_username
    key: secret/data/logging/loki
    property: username
  - name: loki_password
    key: secret/data/logging/loki
    property: password
{{- end }}