{{- if .Values.external_secrets.setup_github_secret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-github"
  namespace: argocd
  labels:
    app: {{ template "bluescape-eks-aux.name" . }}
    chart: {{ template "bluescape-eks-aux.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "bluescape-eks-aux.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: default
data:
  - name: sshPrivateKey
    key: secret/data/token/github
    property: sshPrivateKey
{{- end }}