apiVersion: v1
kind: ConfigMap
metadata:
  name: lacework-config
  namespace: {{ .Release.Namespace }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
data:
  config.json: |
          {"tokens":{"AccessToken":"{{ .Values.laceworkConfig.accessToken }}"}, "serverurl":"{{ .Values.laceworkConfig.serverUrl}}", "tags":{"Env":"{{ .Values.laceworkConfig.env }}", {{- if .Values.laceworkConfig.clustername }} "KubernetesCluster" :"{{ .Values.laceworkConfig.clustername}}" {{- end }}}}
