---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bluescape-nxlog-ce.fullname" . }}
  labels:
    {{- include "bluescape-nxlog-ce.labels" . | nindent 4 }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  nxlog.conf: |-
  {{ .Values.config | nindent 4 }}
