{{- if .Values.grafana.ha_mode }}
apiVersion: v1
data:
  init.sql: |
    CREATE DATABASE grafana;
kind: ConfigMap
metadata:
  labels:
    name: postgres-grafana-init-script
  name: postgres-grafana-init-script
{{- end }}