{{- if .Values.grafana.ha_mode }}
apiVersion: v1
data:
  init.sql: |
    CREATE DATABASE grafana;
    CREATE USER grafana_user;
    ALTER ROLE grafana_user WITH PASSWORD 'grafana_user';
    GRANT ALL PRIVILEGES ON DATABASE grafana TO postgres;
    ALTER DATABASE grafana OWNER TO grafana_user;
kind: ConfigMap
metadata:
  name: postgres-grafana-init-script
  labels:
    name: postgres-grafana-init-script
    {{- include "bluescape-monitoring-grafana.labels" . | nindent 4 }}
{{- end }}