{
 "title": "Linux Node Specific Metrics (prometheus - single)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Uptime",
   "type": "singlestat",
   "description": "Looking at time since system boot timestamp",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"${node_name}\"}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "graph",
   "description": "Looking at time since system boot timestamp",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"${node_name}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% CPU",
   "type": "graph",
   "description": "Taken from prometheus alerts, focused only on dev-logger01 with no constraint on load value",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"${node_name}\"}[1m])) * 100))",
     "legendFormat": "Node= {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU IOWAIT",
   "type": "graph",
   "description": "Taken from prometheus alerts, focused only on dev-logger01 with no constraint on load value",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\",instance=~\"${node_name}\"}[1m])) * 100)",
     "legendFormat": "Node= {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Disk Reads / Writes (kbps)",
   "type": "graph",
   "description": "Taken from prometheus alerts, focused only on dev-logger01 with no constraint on load value",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "avg by(instance) (irate(node_disk_read_bytes_total{instance=~\"${node_name}\"} [1m])) / 1024",
     "legendFormat": "Reads - Node= {{ node_name }}"
    },
    {
     "expr": "(avg by(instance) (irate(node_disk_written_bytes_total{instance=~\"${node_name}\"} [1m])) / 1024)",
     "legendFormat": "Writes - Node= {{ instance }}"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"${node_name}\"} - node_memory_MemAvailable_bytes{instance=~\"${node_name}\"}) / node_memory_MemTotal_bytes{instance=~\"${node_name}\"} * 100",
     "legendFormat": "Node= {{ instance }}"
    }
   ]
  },
  {
   "title": "Load Avg (1 min)",
   "type": "graph",
   "description": "CPU Load Average of 1min",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"${node_name}\"}",
     "legendFormat": "Node = {{ instance }}"
    }
   ]
  },
  {
   "title": "Load Avg (5 min)",
   "type": "graph",
   "description": "CPU Load Average of 1min",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"${node_name}\"}",
     "legendFormat": "Node = {{ instance }}"
    }
   ]
  },
  {
   "title": "Load Avg (15 min)",
   "type": "graph",
   "description": "CPU Load Average of 1min",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load15{instance=~\"${node_name}\"}",
     "legendFormat": "Node = {{ instance }}"
    }
   ]
  }
 ]
}