{
 "title": "Overall Container Metrics",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   { "name": "container_name", "label": "Container Name", "query": "label_values(container)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d,60d"
   },
   { "name": "node_name", "label": "Node Name", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "Avg CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (container) (rate(container_cpu_usage_seconds_total{node=~\"${node_name:regex}\", container=~\"${container_name:regex}\", namespace=~\"${namespace:regex}\"}[1m]))) * 100",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{node=~\"${node_name:regex}\", container=~\"${container_name:regex}\", namespace=~\"${namespace:regex}\"})/1024/1024) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container Disk Reads (kbps)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_fs_reads_bytes_total{container=~\"${container_name:regex}.+\", node=~\"${node_name:regex}\", namespace=~\"${namespace:regex}\"}[1m])) by (container))/1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Disk Writes (kbps)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_fs_writes_bytes_total{pod=~\"${container_name:regex}.+\", node=~\"${node_name:regex}\", namespace=~\"${namespace:regex}\"}[1m])) by (container))/1024",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_network_receive_bytes_total{pod=~\"${container_name:regex}.+\", node=~\"${node_name:regex}\", namespace=~\"${namespace:regex}\"}[5m])) by (namespace))/1024",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Namespace",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{pod=~\"${container_name:regex}.+\", node=~\"${node_name:regex}\", namespace=~\"${namespace:regex}\"}[5m])) by (namespace))/1024",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}