{
 "title": "All Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Node", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node Name",
    "query": "label_values(up{node=~\"${node}\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "% CPU",
   "type": "graph",
   "description": "Taken from prometheus alerts with no constraint on load value",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"${node}\"}[1m])) * 100)))\n",
     "legendFormat": "Node= {{instance}}"
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"${node}\"} - node_memory_MemAvailable_bytes{instance=~\"${node}\"}) / node_memory_MemTotal_bytes{instance=~\"${node}\"} * 100",
     "legendFormat": "Node= {{ instance }}"
    }
   ]
  },
  {
   "title": "Load Avg (1 min)",
   "type": "graph",
   "description": "CPU Load Average of 1min",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"${node}\"}",
     "legendFormat": "Node = {{ instance }}"
    }
   ]
  },
  {
   "title": "% Disk Usage on mounted filesystems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{instance=~\"${node}\", fstype!=\"tmpfs\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\", fstype!=\"rootfs\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\", fstype!=\"rootfs\"}) * 100",
     "legendFormat": "{{ instance }} - {{mountpoint}}"
    }
   ]
  }
 ]
}