{
 "title": "Redis",
 "description": "Dashboard for redis metrics.",
 "tags": [ "redis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Node", "query": "prometheus" },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node_name", "label": "Node Name", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "Redis Stream Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_length{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Client Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_client_errors{node=~\"${node_name:regex}\"}[1m])) ))\n",
     "legendFormat": "Node={{ node }}"
    }
   ]
  },
  {
   "title": "Redis Client Reconnects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_client_reconnects{node=~\"${node_name:regex}\"}[1m])) ))\n",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream History Flush Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_history_flush_errors{node=~\"${node_name:regex}\"}[1m])) ))\n",
     "legendFormat": "Node={{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Pending Entries Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_pending_entries_count{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Pending Entries Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_pending_entries_sum{node=~\"${node_name:regex}\"}[1m])) ))\n",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Claimed Entries Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_claimed_entries_count{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Processed Claimed Entries Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_processed_claimed_entries_sum{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Acked Assigned Entries Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_acked_assigned_entries_sum{node=~\"${node_name}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream History Flushed Runtime Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_history_flush_runtime_count{node=~\"${node_name:regex}\"}[1m])) * 100))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Pending Entries Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_pending_entries_bucket{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream History Flush Runtime Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_history_flush_runtime_count{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  },
  {
   "title": "Redis Stream Acked Claimed Entries Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (avg by(node) (irate(redis_stream_acked_claimed_entries_count{node=~\"${node_name:regex}\"}[1m])) ))",
     "legendFormat": "Node= {{ node }}"
    }
   ]
  }
 ]
}