{
 "title": "Node.Js / HTTP Codes",
 "tags": [
  "bluescape",
  "nodejs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "service",
    "query": "label_values(nodejs_version_info{namespace=~\"${namespace}\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node.Js Http 2xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"2.*\", namespace=~\"${namespace}\"}[5m])) by (status_code, app)",
     "legendFormat": "{{ app }} ({{ status_code }})"
    }
   ]
  },
  {
   "title": "Node.Js Http 3xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"3.*\", namespace=~\"${namespace}\"}[5m])) by (status_code, app)",
     "legendFormat": "{{ app }} ({{ status_code }})"
    }
   ]
  },
  {
   "title": "Node.Js Http 4xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4.*\", namespace=~\"${namespace}\"}[5m])) by (status_code, app)",
     "legendFormat": "{{ app }} ({{ status_code }})"
    }
   ]
  },
  {
   "title": "Node.Js Http 5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5.*\", namespace=~\"${namespace}\"}[5m])) by (status_code, app)",
     "legendFormat": "{{ app }} ({{ status_code }})"
    }
   ]
  }
 ]
}