name: Generate Helm Index

on:
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    # Figure out which files were changed
    - uses: actions/checkout@v1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Get changed helm charts
      id: get-changed-charts
      run: |
        # See which files have changed in this commit
        changed_chart_files=$(git --no-pager diff --name-only HEAD $(git merge-base HEAD origin/main) -- helm-chart-sources )
        echo Changed chart files: ${changed_chart_files[@]}

        mkdir -p .tmp/packages
        changed_charts=()

        for chart_file in $changed_chart_files;
        do
          # Only grab the top two directories
          chart=$(echo $chart_file | awk -F "/" '{print $1"/"$2}')
          # Don't add duplicates
          [[ "${changed_charts[@]}" == *"$chart"* ]] && added="true" || added="false"
          if [ "$added" = "false" ]; then
            changed_charts+=( $chart )
            echo Creating new package for: $chart
            helm package -u -d .tmp/packages $chart
          fi
        done
  
        echo Generating new index
        helm repo index --url https://bluescape.github.io/helm-charts/. --merge index.yaml .tmp

        echo Moving .tmp to packages
        find .tmp/ -name *.tgz | xargs -I '{}' mv '{}' packages/

        echo Move the new merged index
        if [ -f .tmp/index.yaml ]; then
          mv .tmp/index.yaml index.yaml
        fi
        rm -rf .tmp

        echo "::set-output name=changed_charts::[\"${changed_charts// /\", \"}\"]"
    - name: Show diff
      run: git diff
    - name: Commit changes
      if: steps.get-changed-charts.outputs.changed_charts[0] != null
      run: |
        git add .
        git commit -m "Generate packages and update index"
    # Push back the changes
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}
