name: Generate Helm Index

on:
  pull_request:
    paths:
    - helm-chart-sources/**

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    # Figure out which files were changed
    - uses: actions/checkout@v1

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    # This complexity is required due to lack of a feature in helm cli.
    # It creates a new index.yaml without updating the created timestamps of the untouched packages.
    - name: Package Helm Charts
      id: package-charts
      run: ./.github/scripts/package-charts.sh
    - name: Show diff
      run: git diff
    - name: Commit changes
#     if: steps.get-changed-charts.outputs.charts_changed == 'true'
      run: |
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Generate packages and update index"
    # Push back the changes
    - name: Push changes
#     if: steps.get-changed-charts.outputs.charts_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
